library(randomForest)
samplesize <- 991
TrainX <- sample(1:samplesize,round(samplesize*0.8))
TestX <- setdiff(1:samplesize,TrainX)
#SI.Data <- cbind(XData[TrainX,],YData[TrainX,])
SI.Data <- cbind(XData,YData)
colnames(SI.Data) <- c("SPL","SNR","RT","G","BN","SI")
set.seed(20)
#SI.rf <- randomForest(SI ~ ., data=SI.Data, xtest=XData[TestX,],ytest=YData[TestX,], importance=TRUE,proximity=TRUE)
SI.rf <- randomForest(SI ~ ., data=SI.Data, importance=TRUE,proximity=TRUE)
print(SI.rf)
print(round(importance(SI.rf), 2))
varImpPlot(SI.rf)
colnames(XData) <- c("SPL","SNR","RT","G","BN")
SI.Pre <- predict(SI.rf,XData)
write.table(SI.Pre, file = 'PreSIRF_L.txt')
